// Parse app key initializer
//Parse.initialize("O8DRdrCH1swFcLmKGBY6T7SWEuZpzdblkqvi9Ucj", "DTPRIUqThzJpuFBzfhO78acdOSy22q2t5vCax7WH");

// League DEV api key 89fd5947-db70-4995-bcfe-46600a67628f
// Randy's api key 1809d909-de42-4eda-ae26-645323c35f5b

var APIKEY = "1809d909-de42-4eda-ae26-645323c35f5b";
var matchIden = "";
var summonerIden = "";
var participantIden = 0;

var teamGold = [];
var teamKills = [];
var teamTowers = [];
var teamDragons = [];
var teamBarons = [];
var time;
var gameSec;
var gameHour;

var data = {
   "region":"NA",
   "matchType":"MATCHED_GAME",
   "matchCreation":1444188480401,
   "participants":[
      {
         "masteries":[
            {
               "rank":1,
               "masteryId":4111
            },
            {
               "rank":3,
               "masteryId":4113
            },
            {
               "rank":1,
               "masteryId":4121
            },
            {
               "rank":3,
               "masteryId":4123
            },
            {
               "rank":1,
               "masteryId":4133
            },
            {
               "rank":3,
               "masteryId":4134
            },
            {
               "rank":3,
               "masteryId":4143
            },
            {
               "rank":1,
               "masteryId":4144
            },
            {
               "rank":3,
               "masteryId":4152
            },
            {
               "rank":1,
               "masteryId":4154
            },
            {
               "rank":1,
               "masteryId":4162
            },
            {
               "rank":2,
               "masteryId":4211
            },
            {
               "rank":2,
               "masteryId":4212
            },
            {
               "rank":1,
               "masteryId":4221
            },
            {
               "rank":3,
               "masteryId":4222
            },
            {
               "rank":1,
               "masteryId":4232
            }
         ],
         "stats":{
            "unrealKills":0,
            "item2":1052,
            "item1":2003,
            "totalDamageTaken":17385,
            "item0":3020,
            "pentaKills":0,
            "sightWardsBoughtInGame":0,
            "winner":false,
            "magicDamageDealt":110820,
            "wardsKilled":0,
            "largestCriticalStrike":0,
            "trueDamageDealt":1291,
            "doubleKills":2,
            "physicalDamageDealt":8369,
            "tripleKills":0,
            "deaths":6,
            "firstBloodAssist":false,
            "magicDamageDealtToChampions":19772,
            "assists":3,
            "visionWardsBoughtInGame":0,
            "totalTimeCrowdControlDealt":100,
            "champLevel":15,
            "physicalDamageTaken":8123,
            "totalDamageDealt":120481,
            "largestKillingSpree":3,
            "inhibitorKills":0,
            "minionsKilled":183,
            "towerKills":0,
            "physicalDamageDealtToChampions":941,
            "quadraKills":0,
            "goldSpent":9380,
            "totalDamageDealtToChampions":21645,
            "goldEarned":10567,
            "neutralMinionsKilledTeamJungle":1,
            "firstBloodKill":false,
            "firstTowerKill":false,
            "wardsPlaced":4,
            "trueDamageDealtToChampions":932,
            "killingSprees":2,
            "firstInhibitorKill":false,
            "totalScoreRank":0,
            "totalUnitsHealed":1,
            "kills":8,
            "firstInhibitorAssist":false,
            "totalPlayerScore":0,
            "neutralMinionsKilledEnemyJungle":0,
            "magicDamageTaken":8371,
            "largestMultiKill":2,
            "totalHeal":295,
            "item4":1026,
            "item3":3285,
            "objectivePlayerScore":0,
            "item6":3340,
            "firstTowerAssist":false,
            "item5":3157,
            "trueDamageTaken":890,
            "neutralMinionsKilled":1,
            "combatPlayerScore":0
         },
         "runes":[
            {
               "rank":9,
               "runeId":5273
            },
            {
               "rank":9,
               "runeId":5289
            },
            {
               "rank":9,
               "runeId":5316
            },
            {
               "rank":3,
               "runeId":5365
            }
         ],
         "timeline":{
            "xpDiffPerMinDeltas":{
               "zeroToTen":22.49999999999997,
               "tenToTwenty":-63.49999999999997,
               "twentyToThirty":33.5
            },
            "damageTakenDiffPerMinDeltas":{
               "zeroToTen":-29.5,
               "tenToTwenty":109.79999999999998,
               "twentyToThirty":-72.30000000000001
            },
            "xpPerMinDeltas":{
               "zeroToTen":458.6,
               "tenToTwenty":391.1,
               "twentyToThirty":448.1
            },
            "goldPerMinDeltas":{
               "zeroToTen":305.1,
               "tenToTwenty":306.6,
               "twentyToThirty":367.4
            },
            "role":"SOLO",
            "creepsPerMinDeltas":{
               "zeroToTen":6.2,
               "tenToTwenty":5.9,
               "twentyToThirty":5.7
            },
            "csDiffPerMinDeltas":{
               "zeroToTen":-0.8999999999999995,
               "tenToTwenty":-2.6,
               "twentyToThirty":2.7
            },
            "damageTakenPerMinDeltas":{
               "zeroToTen":307.4,
               "tenToTwenty":461,
               "twentyToThirty":545.5
            },
            "lane":"MIDDLE"
         },
         "spell2Id":4,
         "participantId":1,
         "championId":55,
         "teamId":100,
         "highestAchievedSeasonTier":"DIAMOND",
         "spell1Id":14
      },
      {
         "masteries":[
            {
               "rank":4,
               "masteryId":4112
            },
            {
               "rank":1,
               "masteryId":4114
            },
            {
               "rank":3,
               "masteryId":4122
            },
            {
               "rank":1,
               "masteryId":4124
            },
            {
               "rank":1,
               "masteryId":4132
            },
            {
               "rank":3,
               "masteryId":4134
            },
            {
               "rank":2,
               "masteryId":4142
            },
            {
               "rank":1,
               "masteryId":4144
            },
            {
               "rank":1,
               "masteryId":4151
            },
            {
               "rank":3,
               "masteryId":4152
            },
            {
               "rank":1,
               "masteryId":4162
            },
            {
               "rank":2,
               "masteryId":4211
            },
            {
               "rank":2,
               "masteryId":4212
            },
            {
               "rank":1,
               "masteryId":4221
            },
            {
               "rank":3,
               "masteryId":4222
            },
            {
               "rank":1,
               "masteryId":4232
            }
         ],
         "stats":{
            "unrealKills":0,
            "item2":3153,
            "item1":1038,
            "totalDamageTaken":21632,
            "item0":1001,
            "pentaKills":0,
            "sightWardsBoughtInGame":0,
            "winner":false,
            "magicDamageDealt":87,
            "wardsKilled":3,
            "largestCriticalStrike":513,
            "trueDamageDealt":15109,
            "doubleKills":0,
            "physicalDamageDealt":90586,
            "tripleKills":0,
            "deaths":8,
            "firstBloodAssist":false,
            "magicDamageDealtToChampions":87,
            "assists":9,
            "visionWardsBoughtInGame":1,
            "totalTimeCrowdControlDealt":55,
            "champLevel":14,
            "physicalDamageTaken":13273,
            "totalDamageDealt":105783,
            "largestKillingSpree":0,
            "inhibitorKills":0,
            "minionsKilled":165,
            "towerKills":0,
            "physicalDamageDealtToChampions":17078,
            "quadraKills":0,
            "goldSpent":9605,
            "totalDamageDealtToChampions":24060,
            "goldEarned":10106,
            "neutralMinionsKilledTeamJungle":15,
            "firstBloodKill":false,
            "firstTowerKill":false,
            "wardsPlaced":0,
            "trueDamageDealtToChampions":6893,
            "killingSprees":0,
            "firstInhibitorKill":false,
            "totalScoreRank":0,
            "totalUnitsHealed":1,
            "kills":3,
            "firstInhibitorAssist":false,
            "totalPlayerScore":0,
            "neutralMinionsKilledEnemyJungle":0,
            "magicDamageTaken":7216,
            "largestMultiKill":1,
            "totalHeal":1557,
            "item4":3046,
            "item3":2043,
            "objectivePlayerScore":0,
            "item6":3342,
            "firstTowerAssist":false,
            "item5":1037,
            "trueDamageTaken":1143,
            "neutralMinionsKilled":15,
            "combatPlayerScore":0
         },
         "runes":[
            {
               "rank":7,
               "runeId":5245
            },
            {
               "rank":2,
               "runeId":5251
            },
            {
               "rank":4,
               "runeId":5277
            },
            {
               "rank":5,
               "runeId":5289
            },
            {
               "rank":9,
               "runeId":5317
            },
            {
               "rank":3,
               "runeId":5337
            }
         ],
         "timeline":{
            "xpDiffPerMinDeltas":{
               "zeroToTen":-16.200000000000017,
               "tenToTwenty":-18.69999999999999,
               "twentyToThirty":36.900000000000034
            },
            "damageTakenDiffPerMinDeltas":{
               "zeroToTen":23.15000000000002,
               "tenToTwenty":-88.25,
               "twentyToThirty":-163.64999999999992
            },
            "xpPerMinDeltas":{
               "zeroToTen":269.9,
               "tenToTwenty":483.5,
               "twentyToThirty":445.6
            },
            "goldPerMinDeltas":{
               "zeroToTen":241.6,
               "tenToTwenty":330.8,
               "twentyToThirty":337
            },
            "role":"DUO_CARRY",
            "creepsPerMinDeltas":{
               "zeroToTen":5.5,
               "tenToTwenty":5.6,
               "twentyToThirty":5.3
            },
            "csDiffPerMinDeltas":{
               "zeroToTen":-0.3499999999999994,
               "tenToTwenty":1.1500000000000004,
               "twentyToThirty":1.2
            },
            "damageTakenPerMinDeltas":{
               "zeroToTen":400,
               "tenToTwenty":740.5999999999999,
               "twentyToThirty":614.5
            },
            "lane":"BOTTOM"
         },
         "spell2Id":3,
         "participantId":2,
         "championId":67,
         "teamId":100,
         "highestAchievedSeasonTier":"PLATINUM",
         "spell1Id":4
      },
      {
         "masteries":[
            {
               "rank":2,
               "masteryId":4211
            },
            {
               "rank":2,
               "masteryId":4212
            },
            {
               "rank":1,
               "masteryId":4221
            },
            {
               "rank":3,
               "masteryId":4222
            },
            {
               "rank":1,
               "masteryId":4232
            },
            {
               "rank":1,
               "masteryId":4312
            },
            {
               "rank":3,
               "masteryId":4313
            },
            {
               "rank":3,
               "masteryId":4322
            },
            {
               "rank":1,
               "masteryId":4323
            },
            {
               "rank":1,
               "masteryId":4324
            },
            {
               "rank":3,
               "masteryId":4331
            },
            {
               "rank":1,
               "masteryId":4334
            },
            {
               "rank":1,
               "masteryId":4341
            },
            {
               "rank":1,
               "masteryId":4342
            },
            {
               "rank":3,
               "masteryId":4343
            },
            {
               "rank":1,
               "masteryId":4352
            },
            {
               "rank":1,
               "masteryId":4353
            },
            {
               "rank":1,
               "masteryId":4362
            }
         ],
         "stats":{
            "unrealKills":0,
            "item2":1329,
            "item1":2010,
            "totalDamageTaken":22906,
            "item0":3401,
            "pentaKills":0,
            "sightWardsBoughtInGame":0,
            "winner":false,
            "magicDamageDealt":19297,
            "wardsKilled":5,
            "largestCriticalStrike":0,
            "trueDamageDealt":5547,
            "doubleKills":0,
            "physicalDamageDealt":10092,
            "tripleKills":0,
            "deaths":6,
            "firstBloodAssist":false,
            "magicDamageDealtToChampions":6793,
            "assists":6,
            "visionWardsBoughtInGame":4,
            "totalTimeCrowdControlDealt":69,
            "champLevel":13,
            "physicalDamageTaken":11782,
            "totalDamageDealt":34937,
            "largestKillingSpree":2,
            "inhibitorKills":0,
            "minionsKilled":62,
            "towerKills":0,
            "physicalDamageDealtToChampions":2732,
            "quadraKills":0,
            "goldSpent":7960,
            "totalDamageDealtToChampions":10301,
            "goldEarned":8214,
            "neutralMinionsKilledTeamJungle":0,
            "firstBloodKill":false,
            "firstTowerKill":false,
            "wardsPlaced":36,
            "trueDamageDealtToChampions":775,
            "killingSprees":1,
            "firstInhibitorKill":false,
            "totalScoreRank":0,
            "totalUnitsHealed":5,
            "kills":4,
            "firstInhibitorAssist":false,
            "totalPlayerScore":0,
            "neutralMinionsKilledEnemyJungle":0,
            "magicDamageTaken":9426,
            "largestMultiKill":1,
            "totalHeal":3350,
            "item4":3050,
            "item3":1028,
            "objectivePlayerScore":0,
            "item6":3364,
            "firstTowerAssist":false,
            "item5":2049,
            "trueDamageTaken":1697,
            "neutralMinionsKilled":0,
            "combatPlayerScore":0
         },
         "runes":[
            {
               "rank":4,
               "runeId":5289
            },
            {
               "rank":5,
               "runeId":5295
            },
            {
               "rank":6,
               "runeId":5315
            },
            {
               "rank":3,
               "runeId":5331
            },
            {
               "rank":3,
               "runeId":5347
            },
            {
               "rank":9,
               "runeId":5402
            }
         ],
         "timeline":{
            "xpDiffPerMinDeltas":{
               "zeroToTen":-16.200000000000017,
               "tenToTwenty":-18.69999999999999,
               "twentyToThirty":36.900000000000034
            },
            "damageTakenDiffPerMinDeltas":{
               "zeroToTen":23.15000000000002,
               "tenToTwenty":-88.25,
               "twentyToThirty":-163.64999999999992
            },
            "xpPerMinDeltas":{
               "zeroToTen":307.5,
               "tenToTwenty":245.20000000000002,
               "twentyToThirty":452.5
            },
            "goldPerMinDeltas":{
               "zeroToTen":180.8,
               "tenToTwenty":289.7,
               "twentyToThirty":274.6
            },
            "role":"DUO_SUPPORT",
            "creepsPerMinDeltas":{
               "zeroToTen":1.5,
               "tenToTwenty":2.5,
               "twentyToThirty":2.2
            },
            "csDiffPerMinDeltas":{
               "zeroToTen":-0.3499999999999994,
               "tenToTwenty":1.1500000000000004,
               "twentyToThirty":1.2
            },
            "damageTakenPerMinDeltas":{
               "zeroToTen":315.6,
               "tenToTwenty":589.6,
               "twentyToThirty":843.9000000000001
            },
            "lane":"BOTTOM"
         },
         "spell2Id":4,
         "participantId":3,
         "championId":53,
         "teamId":100,
         "highestAchievedSeasonTier":"DIAMOND",
         "spell1Id":14
      },
      {
         "masteries":[
            {
               "rank":1,
               "masteryId":4111
            },
            {
               "rank":4,
               "masteryId":4113
            },
            {
               "rank":3,
               "masteryId":4122
            },
            {
               "rank":1,
               "masteryId":4132
            },
            {
               "rank":2,
               "masteryId":4211
            },
            {
               "rank":2,
               "masteryId":4212
            },
            {
               "rank":1,
               "masteryId":4214
            },
            {
               "rank":1,
               "masteryId":4221
            },
            {
               "rank":3,
               "masteryId":4222
            },
            {
               "rank":1,
               "masteryId":4232
            },
            {
               "rank":3,
               "masteryId":4233
            },
            {
               "rank":3,
               "masteryId":4234
            },
            {
               "rank":1,
               "masteryId":4244
            },
            {
               "rank":3,
               "masteryId":4252
            },
            {
               "rank":1,
               "masteryId":4262
            }
         ],
         "stats":{
            "unrealKills":0,
            "item2":3742,
            "item1":3111,
            "totalDamageTaken":36952,
            "item0":3211,
            "pentaKills":0,
            "sightWardsBoughtInGame":3,
            "winner":false,
            "magicDamageDealt":86282,
            "wardsKilled":4,
            "largestCriticalStrike":0,
            "trueDamageDealt":10519,
            "doubleKills":0,
            "physicalDamageDealt":24801,
            "tripleKills":0,
            "deaths":5,
            "firstBloodAssist":false,
            "magicDamageDealtToChampions":7540,
            "assists":8,
            "visionWardsBoughtInGame":1,
            "totalTimeCrowdControlDealt":832,
            "champLevel":15,
            "physicalDamageTaken":23032,
            "totalDamageDealt":121603,
            "largestKillingSpree":0,
            "inhibitorKills":0,
            "minionsKilled":62,
            "towerKills":0,
            "physicalDamageDealtToChampions":1825,
            "quadraKills":0,
            "goldSpent":8995,
            "totalDamageDealtToChampions":10084,
            "goldEarned":9540,
            "neutralMinionsKilledTeamJungle":56,
            "firstBloodKill":false,
            "firstTowerKill":false,
            "wardsPlaced":5,
            "trueDamageDealtToChampions":718,
            "killingSprees":0,
            "firstInhibitorKill":false,
            "totalScoreRank":0,
            "totalUnitsHealed":1,
            "kills":2,
            "firstInhibitorAssist":false,
            "totalPlayerScore":0,
            "neutralMinionsKilledEnemyJungle":2,
            "magicDamageTaken":12091,
            "largestMultiKill":1,
            "totalHeal":4871,
            "item4":3709,
            "item3":3067,
            "objectivePlayerScore":0,
            "item6":3341,
            "firstTowerAssist":false,
            "item5":0,
            "trueDamageTaken":1828,
            "neutralMinionsKilled":58,
            "combatPlayerScore":0
         },
         "runes":[
            {
               "rank":9,
               "runeId":5247
            },
            {
               "rank":9,
               "runeId":5296
            },
            {
               "rank":9,
               "runeId":5317
            },
            {
               "rank":3,
               "runeId":5357
            }
         ],
         "timeline":{
            "xpDiffPerMinDeltas":{
               "zeroToTen":-141.70000000000005,
               "tenToTwenty":-139.60000000000005,
               "twentyToThirty":-203
            },
            "damageTakenDiffPerMinDeltas":{
               "zeroToTen":107.19999999999999,
               "tenToTwenty":214.09999999999997,
               "twentyToThirty":446.2
            },
            "xpPerMinDeltas":{
               "zeroToTen":296.2,
               "tenToTwenty":493.1,
               "twentyToThirty":497.59999999999997
            },
            "goldPerMinDeltas":{
               "zeroToTen":232.10000000000002,
               "tenToTwenty":330.2,
               "twentyToThirty":316
            },
            "role":"NONE",
            "creepsPerMinDeltas":{
               "zeroToTen":0.2,
               "tenToTwenty":2.4,
               "twentyToThirty":3.2
            },
            "csDiffPerMinDeltas":{
               "zeroToTen":-0.2,
               "tenToTwenty":-0.29999999999999993,
               "twentyToThirty":-3.3
            },
            "damageTakenPerMinDeltas":{
               "zeroToTen":782.9000000000001,
               "tenToTwenty":952,
               "twentyToThirty":1411.4
            },
            "lane":"JUNGLE"
         },
         "spell2Id":4,
         "participantId":4,
         "championId":223,
         "teamId":100,
         "highestAchievedSeasonTier":"DIAMOND",
         "spell1Id":11
      },
      {
         "masteries":[
            {
               "rank":1,
               "masteryId":4111
            },
            {
               "rank":4,
               "masteryId":4113
            },
            {
               "rank":1,
               "masteryId":4114
            },
            {
               "rank":3,
               "masteryId":4122
            },
            {
               "rank":1,
               "masteryId":4124
            },
            {
               "rank":1,
               "masteryId":4131
            },
            {
               "rank":1,
               "masteryId":4132
            },
            {
               "rank":3,
               "masteryId":4134
            },
            {
               "rank":1,
               "masteryId":4141
            },
            {
               "rank":1,
               "masteryId":4144
            },
            {
               "rank":3,
               "masteryId":4152
            },
            {
               "rank":1,
               "masteryId":4162
            },
            {
               "rank":2,
               "masteryId":4211
            },
            {
               "rank":2,
               "masteryId":4212
            },
            {
               "rank":1,
               "masteryId":4221
            },
            {
               "rank":3,
               "masteryId":4222
            },
            {
               "rank":1,
               "masteryId":4232
            }
         ],
         "stats":{
            "unrealKills":0,
            "item2":3071,
            "item1":1055,
            "totalDamageTaken":36805,
            "item0":3083,
            "pentaKills":0,
            "sightWardsBoughtInGame":0,
            "winner":false,
            "magicDamageDealt":0,
            "wardsKilled":0,
            "largestCriticalStrike":0,
            "trueDamageDealt":7620,
            "doubleKills":0,
            "physicalDamageDealt":113412,
            "tripleKills":0,
            "deaths":12,
            "firstBloodAssist":false,
            "magicDamageDealtToChampions":0,
            "assists":2,
            "visionWardsBoughtInGame":0,
            "totalTimeCrowdControlDealt":596,
            "champLevel":15,
            "physicalDamageTaken":20143,
            "totalDamageDealt":121033,
            "largestKillingSpree":0,
            "inhibitorKills":0,
            "minionsKilled":172,
            "towerKills":0,
            "physicalDamageDealtToChampions":12249,
            "quadraKills":0,
            "goldSpent":8835,
            "totalDamageDealtToChampions":14837,
            "goldEarned":9285,
            "neutralMinionsKilledTeamJungle":13,
            "firstBloodKill":false,
            "firstTowerKill":false,
            "wardsPlaced":5,
            "trueDamageDealtToChampions":2587,
            "killingSprees":0,
            "firstInhibitorKill":false,
            "totalScoreRank":0,
            "totalUnitsHealed":1,
            "kills":4,
            "firstInhibitorAssist":false,
            "totalPlayerScore":0,
            "neutralMinionsKilledEnemyJungle":1,
            "magicDamageTaken":13155,
            "largestMultiKill":1,
            "totalHeal":2600,
            "item4":3024,
            "item3":3111,
            "objectivePlayerScore":0,
            "item6":3340,
            "firstTowerAssist":false,
            "item5":1029,
            "trueDamageTaken":3506,
            "neutralMinionsKilled":14,
            "combatPlayerScore":0
         },
         "runes":[
            {
               "rank":8,
               "runeId":5245
            },
            {
               "rank":1,
               "runeId":5251
            },
            {
               "rank":9,
               "runeId":5289
            },
            {
               "rank":9,
               "runeId":5317
            },
            {
               "rank":3,
               "runeId":5335
            }
         ],
         "timeline":{
            "xpDiffPerMinDeltas":{
               "zeroToTen":-148.6,
               "tenToTwenty":-137,
               "twentyToThirty":-43.89999999999998
            },
            "damageTakenDiffPerMinDeltas":{
               "zeroToTen":-104.39999999999998,
               "tenToTwenty":193.29999999999995,
               "twentyToThirty":175
            },
            "xpPerMinDeltas":{
               "zeroToTen":341.8,
               "tenToTwenty":425,
               "twentyToThirty":497.7
            },
            "goldPerMinDeltas":{
               "zeroToTen":215.39999999999998,
               "tenToTwenty":316.1,
               "twentyToThirty":311.2
            },
            "role":"SOLO",
            "creepsPerMinDeltas":{
               "zeroToTen":4.4,
               "tenToTwenty":7.1,
               "twentyToThirty":4.9
            },
            "csDiffPerMinDeltas":{
               "zeroToTen":-2.1,
               "tenToTwenty":-0.10000000000000053,
               "twentyToThirty":-3.8000000000000003
            },
            "damageTakenPerMinDeltas":{
               "zeroToTen":573.3,
               "tenToTwenty":1076,
               "twentyToThirty":1399.5
            },
            "lane":"TOP"
         },
         "spell2Id":12,
         "participantId":5,
         "championId":2,
         "teamId":100,
         "highestAchievedSeasonTier":"MASTER",
         "spell1Id":6
      },
      {
         "masteries":[
            {
               "rank":4,
               "masteryId":4112
            },
            {
               "rank":1,
               "masteryId":4114
            },
            {
               "rank":3,
               "masteryId":4122
            },
            {
               "rank":1,
               "masteryId":4124
            },
            {
               "rank":1,
               "masteryId":4131
            },
            {
               "rank":1,
               "masteryId":4132
            },
            {
               "rank":3,
               "masteryId":4134
            },
            {
               "rank":1,
               "masteryId":4141
            },
            {
               "rank":1,
               "masteryId":4142
            },
            {
               "rank":1,
               "masteryId":4144
            },
            {
               "rank":3,
               "masteryId":4152
            },
            {
               "rank":1,
               "masteryId":4162
            },
            {
               "rank":2,
               "masteryId":4211
            },
            {
               "rank":2,
               "masteryId":4212
            },
            {
               "rank":1,
               "masteryId":4221
            },
            {
               "rank":3,
               "masteryId":4222
            },
            {
               "rank":1,
               "masteryId":4232
            }
         ],
         "stats":{
            "unrealKills":0,
            "item2":3155,
            "item1":3078,
            "totalDamageTaken":30463,
            "item0":1031,
            "pentaKills":0,
            "sightWardsBoughtInGame":1,
            "winner":true,
            "magicDamageDealt":6771,
            "wardsKilled":0,
            "largestCriticalStrike":762,
            "trueDamageDealt":19068,
            "doubleKills":1,
            "physicalDamageDealt":145533,
            "tripleKills":0,
            "deaths":2,
            "firstBloodAssist":false,
            "magicDamageDealtToChampions":2055,
            "assists":6,
            "visionWardsBoughtInGame":1,
            "totalTimeCrowdControlDealt":83,
            "champLevel":17,
            "physicalDamageTaken":22710,
            "totalDamageDealt":171373,
            "largestKillingSpree":10,
            "inhibitorKills":0,
            "minionsKilled":241,
            "towerKills":3,
            "physicalDamageDealtToChampions":15211,
            "quadraKills":0,
            "goldSpent":11278,
            "totalDamageDealtToChampions":21481,
            "goldEarned":14136,
            "neutralMinionsKilledTeamJungle":0,
            "firstBloodKill":false,
            "firstTowerKill":false,
            "wardsPlaced":8,
            "trueDamageDealtToChampions":4214,
            "killingSprees":1,
            "firstInhibitorKill":false,
            "totalScoreRank":0,
            "totalUnitsHealed":1,
            "kills":11,
            "firstInhibitorAssist":false,
            "totalPlayerScore":0,
            "neutralMinionsKilledEnemyJungle":1,
            "magicDamageTaken":5432,
            "largestMultiKill":2,
            "totalHeal":12307,
            "item4":3158,
            "item3":3053,
            "objectivePlayerScore":0,
            "item6":3341,
            "firstTowerAssist":false,
            "item5":3211,
            "trueDamageTaken":2320,
            "neutralMinionsKilled":1,
            "combatPlayerScore":0
         },
         "runes":[
            {
               "rank":9,
               "runeId":5247
            },
            {
               "rank":9,
               "runeId":5290
            },
            {
               "rank":9,
               "runeId":5318
            },
            {
               "rank":3,
               "runeId":5337
            }
         ],
         "timeline":{
            "xpDiffPerMinDeltas":{
               "zeroToTen":148.6,
               "tenToTwenty":137,
               "twentyToThirty":43.89999999999998
            },
            "damageTakenDiffPerMinDeltas":{
               "zeroToTen":104.39999999999998,
               "tenToTwenty":-193.29999999999995,
               "twentyToThirty":-175
            },
            "xpPerMinDeltas":{
               "zeroToTen":490.4,
               "tenToTwenty":562,
               "twentyToThirty":541.5999999999999
            },
            "goldPerMinDeltas":{
               "zeroToTen":322.4,
               "tenToTwenty":555.9,
               "twentyToThirty":368.5
            },
            "role":"SOLO",
            "creepsPerMinDeltas":{
               "zeroToTen":6.5,
               "tenToTwenty":7.2,
               "twentyToThirty":8.7
            },
            "csDiffPerMinDeltas":{
               "zeroToTen":2.1,
               "tenToTwenty":0.10000000000000053,
               "twentyToThirty":3.8000000000000003
            },
            "damageTakenPerMinDeltas":{
               "zeroToTen":677.7,
               "tenToTwenty":882.7,
               "twentyToThirty":1224.5
            },
            "lane":"TOP"
         },
         "spell2Id":12,
         "participantId":6,
         "championId":39,
         "teamId":200,
         "highestAchievedSeasonTier":"MASTER",
         "spell1Id":4
      },
      {
         "masteries":[
            {
               "rank":4,
               "masteryId":4112
            },
            {
               "rank":2,
               "masteryId":4113
            },
            {
               "rank":1,
               "masteryId":4114
            },
            {
               "rank":3,
               "masteryId":4122
            },
            {
               "rank":1,
               "masteryId":4131
            },
            {
               "rank":1,
               "masteryId":4132
            },
            {
               "rank":3,
               "masteryId":4134
            },
            {
               "rank":1,
               "masteryId":4141
            },
            {
               "rank":1,
               "masteryId":4144
            },
            {
               "rank":3,
               "masteryId":4152
            },
            {
               "rank":1,
               "masteryId":4162
            },
            {
               "rank":1,
               "masteryId":4311
            },
            {
               "rank":3,
               "masteryId":4312
            },
            {
               "rank":3,
               "masteryId":4322
            },
            {
               "rank":1,
               "masteryId":4324
            },
            {
               "rank":1,
               "masteryId":4332
            }
         ],
         "stats":{
            "unrealKills":0,
            "item2":3110,
            "item1":3102,
            "totalDamageTaken":27891,
            "item0":3930,
            "pentaKills":0,
            "sightWardsBoughtInGame":0,
            "winner":true,
            "magicDamageDealt":178849,
            "wardsKilled":2,
            "largestCriticalStrike":557,
            "trueDamageDealt":13900,
            "doubleKills":2,
            "physicalDamageDealt":104369,
            "tripleKills":0,
            "deaths":5,
            "firstBloodAssist":false,
            "magicDamageDealtToChampions":12199,
            "assists":5,
            "visionWardsBoughtInGame":0,
            "totalTimeCrowdControlDealt":1966,
            "champLevel":18,
            "physicalDamageTaken":19760,
            "totalDamageDealt":297117,
            "largestKillingSpree":8,
            "inhibitorKills":2,
            "minionsKilled":107,
            "towerKills":1,
            "physicalDamageDealtToChampions":11197,
            "quadraKills":0,
            "goldSpent":14408,
            "totalDamageDealtToChampions":26254,
            "goldEarned":16574,
            "neutralMinionsKilledTeamJungle":78,
            "firstBloodKill":false,
            "firstTowerKill":false,
            "wardsPlaced":1,
            "trueDamageDealtToChampions":2857,
            "killingSprees":2,
            "firstInhibitorKill":true,
            "totalScoreRank":0,
            "totalUnitsHealed":1,
            "kills":10,
            "firstInhibitorAssist":false,
            "totalPlayerScore":0,
            "neutralMinionsKilledEnemyJungle":33,
            "magicDamageTaken":4979,
            "largestMultiKill":2,
            "totalHeal":2170,
            "item4":3211,
            "item3":3078,
            "objectivePlayerScore":0,
            "item6":3341,
            "firstTowerAssist":false,
            "item5":1321,
            "trueDamageTaken":3151,
            "neutralMinionsKilled":111,
            "combatPlayerScore":0
         },
         "runes":[
            {
               "rank":9,
               "runeId":5247
            },
            {
               "rank":9,
               "runeId":5295
            },
            {
               "rank":9,
               "runeId":5317
            },
            {
               "rank":3,
               "runeId":5365
            }
         ],
         "timeline":{
            "xpDiffPerMinDeltas":{
               "zeroToTen":141.70000000000005,
               "tenToTwenty":139.60000000000005,
               "twentyToThirty":203
            },
            "damageTakenDiffPerMinDeltas":{
               "zeroToTen":-107.19999999999999,
               "tenToTwenty":-214.09999999999997,
               "twentyToThirty":-446.2
            },
            "xpPerMinDeltas":{
               "zeroToTen":437.90000000000003,
               "tenToTwenty":632.7,
               "twentyToThirty":700.5999999999999
            },
            "goldPerMinDeltas":{
               "zeroToTen":347.79999999999995,
               "tenToTwenty":543.2,
               "twentyToThirty":607.8
            },
            "role":"NONE",
            "creepsPerMinDeltas":{
               "zeroToTen":0.4,
               "tenToTwenty":2.6999999999999997,
               "twentyToThirty":6.5
            },
            "csDiffPerMinDeltas":{
               "zeroToTen":0.2,
               "tenToTwenty":0.29999999999999993,
               "twentyToThirty":3.3
            },
            "damageTakenPerMinDeltas":{
               "zeroToTen":675.7,
               "tenToTwenty":737.9000000000001,
               "twentyToThirty":965.2
            },
            "lane":"JUNGLE"
         },
         "spell2Id":4,
         "participantId":7,
         "championId":77,
         "teamId":200,
         "highestAchievedSeasonTier":"DIAMOND",
         "spell1Id":11
      },
      {
         "masteries":[
            {
               "rank":2,
               "masteryId":4211
            },
            {
               "rank":2,
               "masteryId":4212
            },
            {
               "rank":1,
               "masteryId":4221
            },
            {
               "rank":3,
               "masteryId":4222
            },
            {
               "rank":1,
               "masteryId":4232
            },
            {
               "rank":3,
               "masteryId":4233
            },
            {
               "rank":2,
               "masteryId":4234
            },
            {
               "rank":2,
               "masteryId":4241
            },
            {
               "rank":3,
               "masteryId":4312
            },
            {
               "rank":1,
               "masteryId":4313
            },
            {
               "rank":3,
               "masteryId":4322
            },
            {
               "rank":1,
               "masteryId":4324
            },
            {
               "rank":3,
               "masteryId":4331
            },
            {
               "rank":1,
               "masteryId":4334
            },
            {
               "rank":1,
               "masteryId":4341
            },
            {
               "rank":1,
               "masteryId":4342
            }
         ],
         "stats":{
            "unrealKills":0,
            "item2":0,
            "item1":2049,
            "totalDamageTaken":26657,
            "item0":3190,
            "pentaKills":0,
            "sightWardsBoughtInGame":0,
            "winner":true,
            "magicDamageDealt":11643,
            "wardsKilled":2,
            "largestCriticalStrike":0,
            "trueDamageDealt":3212,
            "doubleKills":0,
            "physicalDamageDealt":12367,
            "tripleKills":0,
            "deaths":3,
            "firstBloodAssist":false,
            "magicDamageDealtToChampions":7523,
            "assists":20,
            "visionWardsBoughtInGame":1,
            "totalTimeCrowdControlDealt":663,
            "champLevel":15,
            "physicalDamageTaken":12546,
            "totalDamageDealt":27223,
            "largestKillingSpree":2,
            "inhibitorKills":0,
            "minionsKilled":39,
            "towerKills":1,
            "physicalDamageDealtToChampions":3785,
            "quadraKills":0,
            "goldSpent":8971,
            "totalDamageDealtToChampions":11309,
            "goldEarned":10583,
            "neutralMinionsKilledTeamJungle":0,
            "firstBloodKill":false,
            "firstTowerKill":false,
            "wardsPlaced":31,
            "trueDamageDealtToChampions":0,
            "killingSprees":1,
            "firstInhibitorKill":false,
            "totalScoreRank":0,
            "totalUnitsHealed":4,
            "kills":3,
            "firstInhibitorAssist":false,
            "totalPlayerScore":0,
            "neutralMinionsKilledEnemyJungle":0,
            "magicDamageTaken":10490,
            "largestMultiKill":1,
            "totalHeal":4355,
            "item4":3742,
            "item3":3097,
            "objectivePlayerScore":0,
            "item6":3341,
            "firstTowerAssist":false,
            "item5":3117,
            "trueDamageTaken":3620,
            "neutralMinionsKilled":0,
            "combatPlayerScore":0
         },
         "runes":[
            {
               "rank":9,
               "runeId":5245
            },
            {
               "rank":9,
               "runeId":5289
            },
            {
               "rank":9,
               "runeId":5317
            },
            {
               "rank":3,
               "runeId":5365
            }
         ],
         "timeline":{
            "xpDiffPerMinDeltas":{
               "zeroToTen":16.200000000000017,
               "tenToTwenty":18.69999999999999,
               "twentyToThirty":-36.900000000000034
            },
            "damageTakenDiffPerMinDeltas":{
               "zeroToTen":-23.15000000000002,
               "tenToTwenty":88.25,
               "twentyToThirty":163.64999999999992
            },
            "xpPerMinDeltas":{
               "zeroToTen":335.4,
               "tenToTwenty":391.7,
               "twentyToThirty":342.1
            },
            "goldPerMinDeltas":{
               "zeroToTen":218.2,
               "tenToTwenty":339.2,
               "twentyToThirty":263.79999999999995
            },
            "role":"DUO",
            "creepsPerMinDeltas":{
               "zeroToTen":2,
               "tenToTwenty":1.2,
               "twentyToThirty":0.5
            },
            "csDiffPerMinDeltas":{
               "zeroToTen":0.3499999999999994,
               "tenToTwenty":-1.1500000000000004,
               "twentyToThirty":-1.2
            },
            "damageTakenPerMinDeltas":{
               "zeroToTen":291.3,
               "tenToTwenty":804.7,
               "twentyToThirty":1160.1
            },
            "lane":"BOTTOM"
         },
         "spell2Id":4,
         "participantId":8,
         "championId":201,
         "teamId":200,
         "highestAchievedSeasonTier":"DIAMOND",
         "spell1Id":3
      },
      {
         "masteries":[
            {
               "rank":3,
               "masteryId":4113
            },
            {
               "rank":1,
               "masteryId":4114
            },
            {
               "rank":3,
               "masteryId":4123
            },
            {
               "rank":1,
               "masteryId":4124
            },
            {
               "rank":1,
               "masteryId":4133
            },
            {
               "rank":3,
               "masteryId":4134
            },
            {
               "rank":3,
               "masteryId":4143
            },
            {
               "rank":1,
               "masteryId":4144
            },
            {
               "rank":3,
               "masteryId":4152
            },
            {
               "rank":1,
               "masteryId":4154
            },
            {
               "rank":1,
               "masteryId":4162
            },
            {
               "rank":1,
               "masteryId":4311
            },
            {
               "rank":3,
               "masteryId":4313
            },
            {
               "rank":3,
               "masteryId":4322
            },
            {
               "rank":1,
               "masteryId":4324
            },
            {
               "rank":1,
               "masteryId":4334
            }
         ],
         "stats":{
            "unrealKills":0,
            "item2":3113,
            "item1":1056,
            "totalDamageTaken":15061,
            "item0":0,
            "pentaKills":0,
            "sightWardsBoughtInGame":2,
            "winner":true,
            "magicDamageDealt":145054,
            "wardsKilled":2,
            "largestCriticalStrike":0,
            "trueDamageDealt":407,
            "doubleKills":0,
            "physicalDamageDealt":14876,
            "tripleKills":0,
            "deaths":4,
            "firstBloodAssist":false,
            "magicDamageDealtToChampions":18395,
            "assists":7,
            "visionWardsBoughtInGame":2,
            "totalTimeCrowdControlDealt":124,
            "champLevel":15,
            "physicalDamageTaken":7477,
            "totalDamageDealt":160338,
            "largestKillingSpree":2,
            "inhibitorKills":0,
            "minionsKilled":203,
            "towerKills":1,
            "physicalDamageDealtToChampions":1032,
            "quadraKills":0,
            "goldSpent":10230,
            "totalDamageDealtToChampions":19734,
            "goldEarned":11890,
            "neutralMinionsKilledTeamJungle":16,
            "firstBloodKill":false,
            "firstTowerKill":false,
            "wardsPlaced":6,
            "trueDamageDealtToChampions":307,
            "killingSprees":1,
            "firstInhibitorKill":false,
            "totalScoreRank":0,
            "totalUnitsHealed":1,
            "kills":4,
            "firstInhibitorAssist":false,
            "totalPlayerScore":0,
            "neutralMinionsKilledEnemyJungle":5,
            "magicDamageTaken":6286,
            "largestMultiKill":1,
            "totalHeal":2408,
            "item4":3165,
            "item3":3089,
            "objectivePlayerScore":0,
            "item6":3341,
            "firstTowerAssist":false,
            "item5":1314,
            "trueDamageTaken":1298,
            "neutralMinionsKilled":21,
            "combatPlayerScore":0
         },
         "runes":[
            {
               "rank":9,
               "runeId":5289
            },
            {
               "rank":9,
               "runeId":5315
            },
            {
               "rank":3,
               "runeId":5357
            },
            {
               "rank":9,
               "runeId":5402
            }
         ],
         "timeline":{
            "xpDiffPerMinDeltas":{
               "zeroToTen":-22.49999999999997,
               "tenToTwenty":63.49999999999997,
               "twentyToThirty":-33.5
            },
            "damageTakenDiffPerMinDeltas":{
               "zeroToTen":29.5,
               "tenToTwenty":-109.79999999999998,
               "twentyToThirty":72.30000000000001
            },
            "xpPerMinDeltas":{
               "zeroToTen":436.1,
               "tenToTwenty":454.6,
               "twentyToThirty":414.6
            },
            "goldPerMinDeltas":{
               "zeroToTen":271.9,
               "tenToTwenty":384.8,
               "twentyToThirty":307.3
            },
            "role":"SOLO",
            "creepsPerMinDeltas":{
               "zeroToTen":7.1,
               "tenToTwenty":8.5,
               "twentyToThirty":3
            },
            "csDiffPerMinDeltas":{
               "zeroToTen":0.8999999999999995,
               "tenToTwenty":2.6,
               "twentyToThirty":-2.7
            },
            "damageTakenPerMinDeltas":{
               "zeroToTen":336.9,
               "tenToTwenty":351.20000000000005,
               "twentyToThirty":617.8
            },
            "lane":"MIDDLE"
         },
         "spell2Id":12,
         "participantId":9,
         "championId":45,
         "teamId":200,
         "highestAchievedSeasonTier":"MASTER",
         "spell1Id":4
      },
      {
         "masteries":[
            {
               "rank":4,
               "masteryId":4112
            },
            {
               "rank":1,
               "masteryId":4121
            },
            {
               "rank":3,
               "masteryId":4122
            },
            {
               "rank":1,
               "masteryId":4132
            },
            {
               "rank":3,
               "masteryId":4134
            },
            {
               "rank":3,
               "masteryId":4142
            },
            {
               "rank":1,
               "masteryId":4144
            },
            {
               "rank":1,
               "masteryId":4151
            },
            {
               "rank":3,
               "masteryId":4152
            },
            {
               "rank":1,
               "masteryId":4162
            },
            {
               "rank":2,
               "masteryId":4211
            },
            {
               "rank":2,
               "masteryId":4212
            },
            {
               "rank":1,
               "masteryId":4221
            },
            {
               "rank":3,
               "masteryId":4222
            },
            {
               "rank":1,
               "masteryId":4232
            }
         ],
         "stats":{
            "unrealKills":0,
            "item2":3020,
            "item1":3078,
            "totalDamageTaken":19118,
            "item0":1055,
            "pentaKills":0,
            "sightWardsBoughtInGame":0,
            "winner":true,
            "magicDamageDealt":46199,
            "wardsKilled":1,
            "largestCriticalStrike":728,
            "trueDamageDealt":6204,
            "doubleKills":1,
            "physicalDamageDealt":78716,
            "tripleKills":0,
            "deaths":7,
            "firstBloodAssist":false,
            "magicDamageDealtToChampions":10085,
            "assists":9,
            "visionWardsBoughtInGame":0,
            "totalTimeCrowdControlDealt":0,
            "champLevel":15,
            "physicalDamageTaken":9510,
            "totalDamageDealt":131120,
            "largestKillingSpree":4,
            "inhibitorKills":1,
            "minionsKilled":158,
            "towerKills":3,
            "physicalDamageDealtToChampions":14594,
            "quadraKills":0,
            "goldSpent":9278,
            "totalDamageDealtToChampions":26366,
            "goldEarned":12445,
            "neutralMinionsKilledTeamJungle":7,
            "firstBloodKill":true,
            "firstTowerKill":false,
            "wardsPlaced":1,
            "trueDamageDealtToChampions":1687,
            "killingSprees":1,
            "firstInhibitorKill":false,
            "totalScoreRank":0,
            "totalUnitsHealed":3,
            "kills":8,
            "firstInhibitorAssist":false,
            "totalPlayerScore":0,
            "neutralMinionsKilledEnemyJungle":5,
            "magicDamageTaken":8090,
            "largestMultiKill":2,
            "totalHeal":1948,
            "item4":1036,
            "item3":3072,
            "objectivePlayerScore":0,
            "item6":3342,
            "firstTowerAssist":false,
            "item5":0,
            "trueDamageTaken":1517,
            "neutralMinionsKilled":12,
            "combatPlayerScore":0
         },
         "runes":[
            {
               "rank":9,
               "runeId":5245
            },
            {
               "rank":6,
               "runeId":5289
            },
            {
               "rank":3,
               "runeId":5301
            },
            {
               "rank":9,
               "runeId":5317
            },
            {
               "rank":3,
               "runeId":5337
            }
         ],
         "timeline":{
            "xpDiffPerMinDeltas":{
               "zeroToTen":16.200000000000017,
               "tenToTwenty":18.69999999999999,
               "twentyToThirty":-36.900000000000034
            },
            "damageTakenDiffPerMinDeltas":{
               "zeroToTen":-23.15000000000002,
               "tenToTwenty":88.25,
               "twentyToThirty":163.64999999999992
            },
            "xpPerMinDeltas":{
               "zeroToTen":274.4,
               "tenToTwenty":374.4,
               "twentyToThirty":482.20000000000005
            },
            "goldPerMinDeltas":{
               "zeroToTen":292.4,
               "tenToTwenty":335.5,
               "twentyToThirty":334.29999999999995
            },
            "role":"DUO",
            "creepsPerMinDeltas":{
               "zeroToTen":5.699999999999999,
               "tenToTwenty":4.6,
               "twentyToThirty":4.6
            },
            "csDiffPerMinDeltas":{
               "zeroToTen":0.3499999999999994,
               "tenToTwenty":-1.1500000000000004,
               "twentyToThirty":-1.2
            },
            "damageTakenPerMinDeltas":{
               "zeroToTen":378,
               "tenToTwenty":702,
               "twentyToThirty":625.6
            },
            "lane":"BOTTOM"
         },
         "spell2Id":4,
         "participantId":10,
         "championId":42,
         "teamId":200,
         "highestAchievedSeasonTier":"MASTER",
         "spell1Id":7
      }
   ],
   "platformId":"NA1",
   "matchMode":"CLASSIC",
   "participantIdentities":[
      {
         "player":{
            "profileIcon":913,
            "matchHistoryUri":"/v1/stats/player_history/NA1/212351055",
            "summonerName":"Thalies",
            "summonerId":49208816
         },
         "participantId":1
      },
      {
         "player":{
            "profileIcon":915,
            "matchHistoryUri":"/v1/stats/player_history/NA1/46443204",
            "summonerName":"Akashiya Moka",
            "summonerId":31753007
         },
         "participantId":2
      },
      {
         "player":{
            "profileIcon":713,
            "matchHistoryUri":"/v1/stats/player_history/NA1/44927204",
            "summonerName":"Pseudologia",
            "summonerId":30636032
         },
         "participantId":3
      },
      {
         "player":{
            "profileIcon":507,
            "matchHistoryUri":"/v1/stats/player_history/NA1/44860095",
            "summonerName":"Ryuuya",
            "summonerId":30583789
         },
         "participantId":4
      },
      {
         "player":{
            "profileIcon":915,
            "matchHistoryUri":"/v1/stats/player_history/NA1/41992787",
            "summonerName":"Cambrice",
            "summonerId":27401229
         },
         "participantId":5
      },
      {
         "player":{
            "profileIcon":21,
            "matchHistoryUri":"/v1/stats/player_history/NA/34677921",
            "summonerName":"McCashDollar",
            "summonerId":21328540
         },
         "participantId":6
      },
      {
         "player":{
            "profileIcon":556,
            "matchHistoryUri":"/v1/stats/player_history/NA1/43166232",
            "summonerName":"YummiBananas",
            "summonerId":28903785
         },
         "participantId":7
      },
      {
         "player":{
            "profileIcon":752,
            "matchHistoryUri":"/v1/stats/player_history/NA/37714545",
            "summonerName":"BestLucianAfrica",
            "summonerId":23589592
         },
         "participantId":8
      },
      {
         "player":{
            "profileIcon":535,
            "matchHistoryUri":"/v1/stats/player_history/NA/289090",
            "summonerName":"Aerodactyl",
            "summonerId":262255
         },
         "participantId":9
      },
      {
         "player":{
            "profileIcon":527,
            "matchHistoryUri":"/v1/stats/player_history/NA/33441210",
            "summonerName":"Ultimazero",
            "summonerId":20466116
         },
         "participantId":10
      }
   ],
   "matchVersion":"5.19.0.295",
   "teams":[
      {
         "inhibitorKills":0,
         "dominionVictoryScore":0,
         "bans":[
            {
               "pickTurn":1,
               "championId":131
            },
            {
               "pickTurn":3,
               "championId":114
            },
            {
               "pickTurn":5,
               "championId":122
            }
         ],
         "towerKills":1,
         "firstTower":true,
         "firstBlood":false,
         "firstBaron":false,
         "firstInhibitor":false,
         "firstDragon":false,
         "winner":false,
         "vilemawKills":0,
         "baronKills":0,
         "dragonKills":0,
         "teamId":100
      },
      {
         "inhibitorKills":3,
         "dominionVictoryScore":0,
         "bans":[
            {
               "pickTurn":2,
               "championId":82
            },
            {
               "pickTurn":4,
               "championId":41
            },
            {
               "pickTurn":6,
               "championId":16
            }
         ],
         "towerKills":11,
         "firstTower":false,
         "firstBlood":true,
         "firstBaron":true,
         "firstInhibitor":true,
         "firstDragon":true,
         "winner":true,
         "vilemawKills":0,
         "baronKills":1,
         "dragonKills":3,
         "teamId":200
      }
   ],
   "mapId":11,
   "season":"SEASON2015",
   "queueType":"RANKED_SOLO_5x5",
   "matchId":1971445980,
   "matchDuration":1904
}


function getInput(){
 
    var input = $("#sName").val();
    console.log(input);
    summonerIdLookup(input);
}
// Function to get summoner id
function summonerIdLookup(summonername) {

    if (summonername !== "") {
        $.ajax({
            url: 'https://na.api.pvp.net/api/lol/na/v1.4/summoner/by-name/' + summonername + '?api_key=' + APIKEY,
            type: 'GET',
            dataType: 'json',
            data: {

            },
            success: function (json) {

                console.log(json);
                var nameNoSpace = summonername.replace(" ", "");
                var nameLower = nameNoSpace.toLowerCase().trim();
                summonerIden = json[nameLower].id;
                previousGameLookup();

            },
            error: function (XMLHttpRequest, textStatus, errorThrown) {
            }
        });
    }
}

// FORMAT @xxxxxxxxxxxxxxx Team NAMEOFCHARXXXXXX Gold: 101.5k-101.5k Kills: 55-55, Towers: 9-9, Drag: 5-5, Baron: 5-5 Time: 00:00

function previousGameLookup(){
    if (summonerIden !== "") {
        $.ajax({
            
            url: 'https://na.api.pvp.net/api/lol/na/v2.2/matchlist/by-summoner/' + summonerIden + '?beginIndex=0&endIndex=1&api_key=' + APIKEY,
            type: 'GET',
            dataType: 'json',
            data: {

            },
            success: function (json) {

                var matchIden = json[matches].matchId;
                getMatchData(matchIden);
            },
            error: function (XMLHttpRequest, textStatus, errorThrown) {
            }
        });
    }
}

function getMatchData(matchIden){
    
    console.log("hi");
    $.ajax({
        url: 'https://na.api.pvp.net/api/lol/na/v2.2/match/' + matchIden + '?includeTimeline=false&api_key=' + APIKEY,
        type: 'GET',
        dataType: 'json',
        data: {

        },
        success: function (json) {
            getParticipantId(json);
            getTotalData(json);
        
        },
        error: function (XMLHttpRequest, textStatus, errorThrown) {
        }
    });
}



function getParticipantId(teamJson){
 
    for(var i = 0; i< 10; i++){
        var tempParticipant = teamJson.participantsIdentities[i];
        if(tempParticipant[player].summonerId === summonerIden)
            participantIden = tempParticipant.participantId;
        
    }
}


// FORMAT @xxxxxxxxxxxxxxx Team NAMEOFCHARXXXXXX Gold: 101.5k-101.5k Kills: 55-55, Towers: 9-9, Drag: 5-5, Baron: 5-5 Time: 00:00

function getTotalData(teamJson){
    
    // Gets team 1
    for (var i = 0; i < 10; ++i) {

        // Gets the current Team member
        var tempParticipant = teamJson.participants[i];
        var tempTeamId = teamJson.participants[i].teamId;
        var index = (((tempTeamId)/100) - 1);
        teamKills[index] += tempParticipant.stats.kills;
        teamGold[index] += tempParticipant.stats.goldEarned;
        
    }
    
    //Getting total team data
    for(var i = 0; i < 2; i++){
        var tempTeam = teamJson.teams[i];
        var tempTeamId = tempTeam.teamId;
        var index = (((tempTeamId)/100) - 1);
        teamBarons[index] = tempTeam.baronKills;
        teamDragons[index] = tempTeam.dragonKills;
        teamTowers[index] = tempTeam.towerKills;
    }
    
    gameSec = ((teamJson.matchDuration) % 60)
    gimeMin =((teamJson.matchDuration)/60)
console.log(teamGold);
console.log(teamKills);
console.log(teamTowers);
console.log(teamDragons);
console.log(teamBarons);

}
